@baseUrl = http://localhost:3333

@auth_token = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Fulano Sousa",
    "email": "fulano@gmail.com",
    "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "fulano@gmail.com",
    "password": "123456"
}

###

# @name shorten_url
POST {{baseUrl}}/shorten
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "url": "https://teddy360.com.br/material/marco-legal-das-garantias-sancionado-entenda-o-que-muda/"
}