@baseUrl = http://localhost:3333

@auth_token = {{authenticate.response.body.access_token}}

####################################################################################################
# O Objetivo desta rota [e realizar o cadastro do usuário na aplicação
####################################################################################################

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Fulano Sousa",
    "email": "fulano2@gmail.com",
    "password": "123456"
}

####################################################################################################
# O Objetivo desta rota é realizar a autenticação do usuário
# OBS: Após a realização da autenticação com sucesso o access_token é preenchido automaticamente
####################################################################################################

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "fulano2@gmail.com",
    "password": "123456"
}

####################################################################################################
# O Objetivo desta rota é realizar o encurtamento da URL
####################################################################################################

# @name create_shorten_url
POST {{baseUrl}}/shorten
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "url": "https://teddy360.com.br/material/marco-legal-das-garantias-sancionado-entenda-o-que-muda/"
}


####################################################################################################
# O Objetivo desta rota é realizar a atualização do endereço de origem da rota
# OBS: Primeiro você tem que adquerir o ID da URL, que pode ser na rota de listagem de URLS
# ou acessando o banco de dados
####################################################################################################

# @name update_url_destiny
PUT {{baseUrl}}/shorten
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "urlId": "0350be3f-5ce3-409e-8299-08d8f8d5f0d9",
    "newdestinyUrl": "https://github.com/pedrohigordev/challenge-url-shortener"
}

####################################################################################################
# O Objetivo desta rota é realizar o soft delete da URL cadastrada
# OBS: Primeiro você tem que adquerir o ID da URL, que pode ser na rota de listagem de URLS
# ou acessando o banco de dados
####################################################################################################

# @name delete_url
DELETE  {{baseUrl}}/shorten?urlId=2f5d76f3-f871-4af7-a7f1-6386b5bba35f
Content-Type: application/json
Authorization: Bearer {{auth_token}}


####################################################################################################
# O Objetivo desta rota é listar todas as URls do usuário autenticado
####################################################################################################

# @name list_urls
GET  {{baseUrl}}/shorten
Content-Type: application/json
Authorization: Bearer {{auth_token}}


####################################################################################################
# O Objetivo desta rota é realizar o acesso e redirecionamento da Url encurtada através do hash
####################################################################################################

# @name access_url_shortened
GET  {{baseUrl}}/tXGvIf
Content-Type: application/json
Authorization: Bearer {{auth_token}}