@baseUrl = http://localhost:3333

@auth_token = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Fulano Sousa",
    "email": "fulano@gmail.com",
    "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "fulano@gmail.com",
    "password": "123456"
}

###

# @name shorten_url
POST {{baseUrl}}/shorten
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "url": "https://teddy360.com.br/material/marco-legal-das-garantias-sancionado-entenda-o-que-muda/"
}


###

# @name update_url_destiny
PUT {{baseUrl}}/shorten
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "urlId": "c52f4a66-6492-43c0-83c6-76038da4b006",
    "newdestinyUrl": "https://app.rocketseat.com.br/classroom/nest-js/group/fundamentos-do-nest/lesson/criando-decorator-de-autenticacao"
}

###

# @name delete_url
DELETE  {{baseUrl}}/shorten?urlId=b06655dc-7571-4b75-b774-77e4c817bc43
Content-Type: application/json
Authorization: Bearer {{auth_token}}


###

# @name list_urls
GET  {{baseUrl}}/shorten
Content-Type: application/json
Authorization: Bearer {{auth_token}}


###

# @name access_url_shortened
GET  {{baseUrl}}/access-shortened?url=http://localhost/sOGy3B
Content-Type: application/json
Authorization: Bearer {{auth_token}}