version: '3.8'

services:
  postgres:
    container_name: pg-url-shortener
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: teddy-postgres
      POSTGRES_PASSWORD: teddy@2024
      POSTGRES_DB: shortener-db
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
