version: '3.8'

networks:
  url-shortener-net:
    driver: bridge

services:
  postgres:
    container_name: pg_url_shortener
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: teddy-postgres
      POSTGRES_PASSWORD: teddy@2024
      POSTGRES_DB: shortener-db
    networks:
      - url-shortener-net
